<?php

/**
 * @file
 * Contains inmobiliario.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function inmobiliario_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the inmobiliario module.
    case 'help.page.inmobiliario':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for inmobiliario admin') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function inmobiliario_theme() {
  return [
    'inmobiliario' => [
      'render element' => 'children',
    ],
  ];
}
